/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JacketTestRouteImport } from './routes/jacket-test'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SchoolsRouteImport } from './routes/schools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JacketTestRoute = JacketTestRouteImport.update({
  id: '/jacket-test',
  path: '/jacket-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jacket-test': typeof JacketTestRoute
  '/sales': typeof SalesRoute
  '/schools': typeof SchoolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jacket-test': typeof JacketTestRoute
  '/sales': typeof SalesRoute
  '/schools': typeof SchoolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jacket-test': typeof JacketTestRoute
  '/sales': typeof SalesRoute
  '/schools': typeof SchoolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jacket-test' | '/sales' | '/schools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jacket-test' | '/sales' | '/schools'
  id: '__root__' | '/' | '/jacket-test' | '/sales' | '/schools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JacketTestRoute: typeof JacketTestRoute
  SalesRoute: typeof SalesRoute
  SchoolsRoute: typeof SchoolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jacket-test': {
      id: '/jacket-test'
      path: '/jacket-test'
      fullPath: '/jacket-test'
      preLoaderRoute: typeof JacketTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JacketTestRoute: JacketTestRoute,
  SalesRoute: SalesRoute,
  SchoolsRoute: SchoolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
